cleaned up output

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -319,7 +319,7 @@ cd $output
 echo -e "Running Bakta"
 echo -e ""
 
-bakta --threads "$thread" --proteins $BEAV_DIR/databases/bakta_custom_protein/combined.faa --strain "$strain" --output $strain --skip-plot --keep-contig-headers $bakta_args $input_file | tee bakta.log || error_exit "error occurred while running bakta"
+bakta --threads "$thread" --proteins $BEAV_DIR/databases/bakta_custom_protein/combined.faa --strain "$strain" --output $strain --skip-plot --keep-contig-headers $bakta_args $input_file || error_exit "error occurred while running bakta"
 
 echo -e ""
 echo -e "Done"
@@ -332,15 +332,16 @@ echo -e ""
 
 cd $strain
 
+touch borders.log
 if $agrobacterium_run; then
-	nhmmer --tblout "$strain".leftborder $BEAV_DIR/models/T-DNA_leftborder.hmm "$input_file" 
-	nhmmer --tblout "$strain".rightborder $BEAV_DIR/models/T-DNA_rightborder.hmm "$input_file" 
+	nhmmer --tblout "$strain".leftborder $BEAV_DIR/models/T-DNA_leftborder.hmm "$input_file" >> borders.log 
+	nhmmer --tblout "$strain".rightborder $BEAV_DIR/models/T-DNA_rightborder.hmm "$input_file" >> borders.log
+	nhmmer --tblout "$strain".overdrive $BEAV_DIR/models/overdrive.hmm "$input_file" >> borders.log
 fi
 
-nhmmer --tblout "$strain".dif $BEAV_DIR/models/dif.hmm "$input_file" 
-nhmmer --tblout "$strain".overdrive $BEAV_DIR/models/overdrive.hmm "$input_file" 
-nhmmer --tblout "$strain".nodbox $BEAV_DIR/models/nodbox.hmm "$input_file" 
-nhmmer --tblout "$strain".ttsbox $BEAV_DIR/models/ttsbox.hmm "$input_file"  
+nhmmer --tblout "$strain".dif $BEAV_DIR/models/dif.hmm "$input_file" >> borders.log
+nhmmer --tblout "$strain".nodbox $BEAV_DIR/models/nodbox.hmm "$input_file" >> borders.log
+nhmmer --tblout "$strain".ttsbox $BEAV_DIR/models/ttsbox.hmm "$input_file"  >> borders.log
 fuzznuc --sequence "$input_file" --pattern RTTDCAWWTGHAAY -outfile ${strain}.virbox -rformat excel --complement 
 fuzznuc --sequence "$input_file" --pattern WNGTGMARAWYTGCACDW -outfile ${strain}.trabox -rformat excel --complement 
 fuzznuc -pattern 'GGAAC[CT]N(15,17)CCACNNA' -sequence "$input_file" -complement -outfile ${strain}.hrp_box.out -rformat excel 
@@ -376,6 +377,20 @@ cut -f 1-3,5 ./${strain}.pip_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t
 cut -f 1-3,5 ./${strain}.hrp_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\thrpbox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed
 bedtools intersect -v -nonamecheck -a borders.bed -b ./${strain}.nofasta.gff3 > ./${strain}_borders.table 
 
+mkdir borders
+mv ./${strain}.virbox ./borders/
+mv ./${strain}.trabox ./borders/
+mv ./${strain}.pip_box.out ./borders/
+mv ./${strain}.hrp_box.out ./borders/
+mv ./${strain}.nodbox ./borders/
+mv ./${strain}.ttsbox ./borders/
+mv .${strain}.dif ./borders/ 
+if $agrobacterium_run; then
+	mv ${strain}.leftborder  ./borders/${strain}.left_T-DNA_border 
+	mv ${strain}.rightborder  ./borders/${strain}.right_T-DNA_border
+	mv ${strain}.overdrive  ./borders/
+fi
+
 echo -e ""
 echo -e "----------------------------------------------------------"
 echo -e ""
@@ -399,8 +414,9 @@ echo -e ""
 
 if $macsyfinder_run; then
 	python $BEAV_DIR/scripts/makegembase.py
-	macsyfinder -o macsyfinder_TXSS --db-type gembase --sequence-db allgembase.faa --worker 1 --models TXSScan all > macsyfinder.log || error_exit "error occurred while running macsyfinder"
-	cut -f 2,3 ./macsyfinder_TXSS/best_solution.tsv | sed 's/^\S\+_//g' | sed 's/=/_/g' | grep '	' | grep -v gene_name > macsyfinder.tsv.table
+	macsyfinder -o MacSyFinder_TXSS --db-type gembase --sequence-db allgembase.faa --worker 1 --models TXSScan all > MacSyFinder.log || error_exit "error occurred while running macsyfinder"
+	cut -f 2,3 ./MacSyFinder_TXSS/best_solution.tsv | sed 's/^\S\+_//g' | sed 's/=/_/g' | grep '	' | grep -v gene_name > macsyfinder.tsv.table
+	mv allgembase* ./MacSyFinder_TXSS/
 fi
 
 echo -e ""
@@ -411,9 +427,9 @@ echo -e ""
 echo -e "Identifying integrons (IntegronFinder)"
 echo -e ""
 if $integronfinder_run; then
-    integron_finder --local-max --cpu "$thread" --outdir integron_finder --promoter-attI --pdf  "$input_file" | tee integronfinder.log || error_exit "error occurred while running integron-finder" 
- 	cut -f 2-6,11 ./integron_finder/Results_Integron_Finder_${strain}/${strain}.integrons | awk '$2 ~/P_in|att/' > integron.table
- 	cat ./integron_finder/Results_Integron_Finder_${strain}/${strain}.integrons | grep "	intI	" | cut -f 2,4-5 | bedtools intersect -a - -b ${strain}.nofasta.gff3 -wb -F 0.5 | grep "CDS" | sed -n 's/^.*locus_tag=\([a-zA-Z0-9_]*\);.*$/\1/p' > integron_gene.table 	
+    integron_finder --local-max --cpu "$thread" --outdir Integron_Finder --promoter-attI --pdf  "$input_file" | tee Integron_Finder.log || error_exit "error occurred while running integron-finder" 
+ 	cut -f 2-6,11 ./Integron_Finder/Results_Integron_Finder_${strain}/${strain}.integrons | awk '$2 ~/P_in|att/' > integron.table
+ 	cat ./Integron_Finder/Results_Integron_Finder_${strain}/${strain}.integrons | grep "	intI	" | cut -f 2,4-5 | bedtools intersect -a - -b ${strain}.nofasta.gff3 -wb -F 0.5 | grep "CDS" | sed -n 's/^.*locus_tag=\([a-zA-Z0-9_]*\);.*$/\1/p' > integron_gene.table 	
 fi
 echo -e ""
 echo -e "Done"
@@ -437,8 +453,8 @@ echo -e "Identifying biosynthetic gene clusters (antiSMASH)"
 echo -e ""
 
 if [ "$antismash_run" ]; then
-    antismash --minimal ${strain}.gbff --output-dir antismash > antismash.log || error_exit "error occurred while running antiSMASH" 
-    python $BEAV_DIR/scripts/antismash_genbanks_to_table.py -i./antismash > ${strain}_antismash.table
+    antismash --minimal ${strain}.gbff --output-dir antiSMASH || error_exit "error occurred while running antiSMASH" 
+    python $BEAV_DIR/scripts/antismash_genbanks_to_table.py -i./antiSMASH > ${strain}_antismash.table
     cut -f 4-5 ./${strain}_antismash.table | grep -v "gene_id" > antismash_locustags.table
 fi
 
@@ -453,8 +469,8 @@ echo -e ""
 if $dbscanswa_run; then
 	cp ${strain}.gbff ${strain}.gbk
 	sed -i 's/gnl|Bakta|//g' ${strain}.gbk
-	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}.gbk --output ${strain}.dbscan.swa.out --thread_num "$thread" > dbscan-swa.log || error_exit "error occurred while running DBSCAN-SWA"
-	cut -f 2,5-8 ./${strain}.dbscan.swa.out/bac_DBSCAN-SWA_prophage_summary.txt | grep -v "bacteria_id" > prophage.table
+	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}.gbk --output DBSCAN-SWA --thread_num "$thread" | tee dbscan-swa.log || error_exit "error occurred while running DBSCAN-SWA"
+	cut -f 2,5-8 ./DBSCAN-SWA/bac_DBSCAN-SWA_prophage_summary.txt | grep -v "bacteria_id" > prophage.table
 fi
 
 echo -e ""
@@ -491,6 +507,24 @@ echo -e "Combining annotations and preparing final output files"
 
 cd ..
 python $BEAV_DIR/scripts/combine_annotations.py "$strain" 
+
+mkdir ${strain}/bakta
+
+mv ${strain}/${strain}.txt ${strain}/bakta/
+mv ${strain}/${strain}.embl ${strain}/bakta/
+mv ${strain}/${strain}.faa ${strain}/bakta/
+mv ${strain}/${strain}.faa.idx ${strain}/bakta/
+mv ${strain}/${strain}.ffn ${strain}/bakta/
+mv ${strain}/${strain}.fna ${strain}/bakta/
+mv ${strain}/${strain}.gbff ${strain}/bakta/
+mv ${strain}/${strain}.gbk ${strain}/bakta/
+mv ${strain}/${strain}.gff3 ${strain}/bakta/
+mv ${strain}/${strain}.json ${strain}/bakta/
+mv ${strain}/${strain}.nofasta.gff3 ${strain}/bakta/
+mv ${strain}/${strain}.tsv ${strain}/bakta/
+
+echo -e ""
+echo -e "Final annotation output: ${strain}_final.gbk"
 
 echo -e ""
 echo -e "Done"
@@ -539,7 +573,7 @@ fi
 echo -e ""
 
 if $antismash_run; then
-	antversion=`grep 'antiSMASH version' $output/${strain}/antismash/index.html | sed 's/^.*version //g'`
+	antversion=`grep 'antiSMASH version' $output/${strain}/antiSMASH/index.html | sed 's/^.*version //g'`
 	echo -e "antiSMASH version $antversion"
     echo -e 'Kai Blin, Simon Shaw, Alexander M Kloosterman, Zach Charlop-Powers, Gilles P van Weezel, Marnix H Medema, & Tilmann Weber. 2021. Nucleic Acids Research DOI:10.1093/nar/gkab335.'
 fi
