Update defense_finder call line

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -711,7 +711,7 @@ fi
 
 if $defensefinder_run; then
 	SECONDS=0
-	defense-finder run --db-type gembase ./bakta/${strain}.faa > defensefinder.log|| error_exit "error occurred while running DefenseFinder. Please see defensefinder.log" | tee -a Beav.log
+	defense-finder run --db-type gembase ./bakta/${strain}.faa > defensefinder.log || error_exit "error occurred while running DefenseFinder. Please see defensefinder.log" | tee -a Beav.log
 	ELAPSED="Elapsed: $(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
 	echo $ELAPSED | tee -a Beav.log
 	cut -f 2,3 ./${strain}_defense_finder_genes.tsv | grep -v 'hit_id' > ${strain}_defensefinder.tsv.table
