more fixes

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -312,7 +312,7 @@ cd $output
 echo -e "Running Bakta"
 echo -e ""
 
-bakta --threads "$thread" --proteins $BEAV_DIR/databases/bakta_custom_protein/combined.faa --strain "$strain" --output $strain --skip-plot --keep-contig-headers $bakta_args $input_file  || error_exit "error occurred while running bakta"
+bakta --threads "$thread" --proteins $BEAV_DIR/databases/bakta_custom_protein/combined.faa --strain "$strain" --output $strain --skip-plot --keep-contig-headers $bakta_args $input_file | tee bakta.log || error_exit "error occurred while running bakta"
 
 echo -e ""
 echo -e "Done"
@@ -326,18 +326,18 @@ echo -e ""
 cd $strain
 
 if $agrobacterium_run; then
-	nhmmer --tblout "$strain".leftborder $BEAV_DIR/models/T-DNA_leftborder.hmm "$input_file" || error_exit "error occurred while running nhmmer"
-	nhmmer --tblout "$strain".rightborder $BEAV_DIR/models/T-DNA_rightborder.hmm "$input_file" || error_exit "error occurred while running nhmmer"
+	nhmmer --tblout "$strain".leftborder $BEAV_DIR/models/T-DNA_leftborder.hmm "$input_file" 
+	nhmmer --tblout "$strain".rightborder $BEAV_DIR/models/T-DNA_rightborder.hmm "$input_file" 
 fi
 
-nhmmer --tblout "$strain".dif $BEAV_DIR/models/dif.hmm "$input_file" || error_exit "error occurred while running nhmmer"
-nhmmer --tblout "$strain".overdrive $BEAV_DIR/models/overdrive.hmm "$input_file" || error_exit "error occurred while running nhmmer"
-nhmmer --tblout "$strain".nodbox $BEAV_DIR/models/nodbox.hmm "$input_file" || error_exit "error occurred while running nhmmer"
-nhmmer --tblout "$strain".ttsbox $BEAV_DIR/models/ttsbox.hmm "$input_file"  || error_exit "error occurred while running nhmmer"
-fuzznuc --sequence "$input_file" --pattern RTTDCAWWTGHAAY -outfile ${strain}.virbox -rformat excel --complement || error_exit "error occurred while running fuzznuc"
-fuzznuc --sequence "$input_file" --pattern WNGTGMARAWYTGCACDW -outfile ${strain}.trabox -rformat excel --complement || error_exit "error occurred while running fuzznuc"
-fuzznuc -pattern 'GGAAC[CT]N(15,17)CCACNNA' -sequence "$input_file" -complement -outfile ${strain}.hrp_box.out -rformat excel || error_exit "error occurred while running fuzznuc"
-fuzznuc -pattern 'TTCGBN(15)TTCGB' -sequence "$input_file" -complement -outfile ${strain}.pip_box.out -rformat excel || error_exit "error occurred while running fuzznuc" 
+nhmmer --tblout "$strain".dif $BEAV_DIR/models/dif.hmm "$input_file" 
+nhmmer --tblout "$strain".overdrive $BEAV_DIR/models/overdrive.hmm "$input_file" 
+nhmmer --tblout "$strain".nodbox $BEAV_DIR/models/nodbox.hmm "$input_file" 
+nhmmer --tblout "$strain".ttsbox $BEAV_DIR/models/ttsbox.hmm "$input_file"  
+fuzznuc --sequence "$input_file" --pattern RTTDCAWWTGHAAY -outfile ${strain}.virbox -rformat excel --complement 
+fuzznuc --sequence "$input_file" --pattern WNGTGMARAWYTGCACDW -outfile ${strain}.trabox -rformat excel --complement 
+fuzznuc -pattern 'GGAAC[CT]N(15,17)CCACNNA' -sequence "$input_file" -complement -outfile ${strain}.hrp_box.out -rformat excel 
+fuzznuc -pattern 'TTCGBN(15)TTCGB' -sequence "$input_file" -complement -outfile ${strain}.pip_box.out -rformat excel 
 
 touch borders.table
 
@@ -367,7 +367,7 @@ cut -f 1-3,5 ./${strain}.virbox | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\t
 cut -f 1-3,5 ./${strain}.trabox | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\ttrabox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed    
 cut -f 1-3,5 ./${strain}.pip_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\tpipbox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed
 cut -f 1-3,5 ./${strain}.hrp_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\thrpbox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed
-bedtools intersect -v -nonamecheck -a borders.bed -b ./${strain}.nofasta.gff3 > ./${strain}_borders.table || error_exit "error occurred while running bedtools"
+bedtools intersect -v -nonamecheck -a borders.bed -b ./${strain}.nofasta.gff3 > ./${strain}_borders.table 
 
 echo -e ""
 echo -e "----------------------------------------------------------"
@@ -392,8 +392,8 @@ echo -e ""
 
 if $macsyfinder_run; then
 	python $BEAV_DIR/scripts/makegembase.py
-	macsyfinder -o ${strain}_macsyfinder_TXSS --db-type gembase --sequence-db allgembase.faa --worker 1 --models TXSScan all || error_exit "error occurred while running macsyfinder"
-	cut -f 2,3 ./${strain}_macsyfinder_TXSS/best_solution.tsv | sed 's/^\S\+_//g' | sed 's/=/_/g' | grep '	' | grep -v gene_name > macsyfinder.tsv.table
+	macsyfinder -o macsyfinder_TXSS --db-type gembase --sequence-db allgembase.faa --worker 1 --models TXSScan all > macsyfinder.log || error_exit "error occurred while running macsyfinder"
+	cut -f 2,3 ./macsyfinder_TXSS/best_solution.tsv | sed 's/^\S\+_//g' | sed 's/=/_/g' | grep '	' | grep -v gene_name > macsyfinder.tsv.table
 fi
 
 echo -e ""
@@ -404,7 +404,7 @@ echo -e ""
 echo -e "Identifying integrons (IntegronFinder)"
 echo -e ""
 if $integronfinder_run; then
-    integron_finder --local-max --cpu "$thread" --outdir integron_finder --promoter-attI --pdf  "$input_file" || error_exit "error occurred while running integron-finder" 
+    integron_finder --local-max --cpu "$thread" --outdir integron_finder --promoter-attI --pdf  "$input_file" | tee integronfinder.log || error_exit "error occurred while running integron-finder" 
  	cut -f 2-6,11 ./integron_finder/Results_Integron_Finder_${strain}/${strain}.integrons | awk '$2 ~/P_in|att/' > integron.table
  	cat ./integron_finder/Results_Integron_Finder_${strain}/${strain}.integrons | grep "	intI	" | cut -f 2,4-5 | bedtools intersect -a - -b ${strain}.nofasta.gff3 -wb -F 0.5 | grep "CDS" | sed -n 's/^.*locus_tag=\([a-zA-Z0-9_]*\);.*$/\1/p' > integron_gene.table 	
 fi
@@ -417,7 +417,7 @@ echo -e "Identifying defense systems (DefenseFinder)"
 echo -e ""
 
 if $defensefinder_run; then
-	defense-finder run --db-type gembase ${strain}.faa || error_exit "error occurred while running defense-finder"
+	defense-finder run --db-type gembase ${strain}.faa > defensefinder.log || error_exit "error occurred while running defense-finder"
 	cut -f 2,3 ./defense_finder_genes.tsv | grep -v 'hit_id' > ${strain}_defensefinder.tsv.table
 fi	
 
@@ -430,8 +430,8 @@ echo -e "Identifying biosynthetic gene clusters (antiSMASH)"
 echo -e ""
 
 if [ "$antismash_run" ]; then
-    antismash --minimal ${strain}.gbff --output-dir ${strain}_antismash || error_exit "error occurred while running antismash" 
-    python $BEAV_DIR/scripts/antismash_genbanks_to_table.py -i./${strain}_antismash > ${strain}_antismash.table
+    antismash --minimal ${strain}.gbff --output-dir antismash > antismash.log || error_exit "error occurred while running antiSMASH" 
+    python $BEAV_DIR/scripts/antismash_genbanks_to_table.py -i./antismash > ${strain}_antismash.table
     cut -f 4-5 ./${strain}_antismash.table | grep -v "gene_id" > antismash_locustags.table
 fi
 
@@ -446,7 +446,7 @@ echo -e ""
 if $dbscanswa_run; then
 	cp ${strain}.gbff ${strain}.gbk
 	sed -i 's/gnl|Bakta|//g' ${strain}.gbk
-	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}.gbk --output ${strain}.dbscan.swa.out --thread_num "$thread" || error_exit "error occurred while running DBSCAN-SWA"
+	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}.gbk --output ${strain}.dbscan.swa.out --thread_num "$thread" > dbscan-swa.log || error_exit "error occurred while running DBSCAN-SWA"
 	cut -f 2,5-8 ./${strain}.dbscan.swa.out/bac_DBSCAN-SWA_prophage_summary.txt | grep -v "bacteria_id" > prophage.table
 fi
 
@@ -483,7 +483,7 @@ echo -e ""
 echo -e "Combining annotations and preparing final output files"
 
 cd ..
-python $BEAV_DIR/scripts/combine_annotations.py "$strain" || error_exit "error occurred while combining annotations"
+python $BEAV_DIR/scripts/combine_annotations.py "$strain" 
 
 echo -e ""
 echo -e "Done"
