beav usearch check

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -280,6 +280,13 @@ then
     else
         echo "GapMind: OK"
     fi
+	
+	if ! usearch &> /dev/null
+	then
+		echo "usearch: ERROR"
+	else
+		echo "usearch: OK"
+	fi
 else
 	echo "GapMind: skipped"
 fi
