fixed border order

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -386,7 +386,7 @@ cut -f 1-3,5 ./${strain}.virbox | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\t
 cut -f 1-3,5 ./${strain}.trabox | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\ttrabox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed    
 cut -f 1-3,5 ./${strain}.pip_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\tpipbox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed
 cut -f 1-3,5 ./${strain}.hrp_box.out | grep -v 'SeqName' | sed 's/\t\(\S\+\)$/\t100\thrpbox\t\1/g' | sed 's/+/+1/g' | sed 's/\t-/\t-1/g' >> borders.bed
-bedtools intersect -v -nonamecheck -a borders.bed -b ./${strain}.nofasta.gff3 > ./${strain}_borders.table 
+awk '$2 > $3 { s=$2; $2=$3; $3=s }' borders.bed | bedtools intersect -v -nonamecheck -a - -b ./${strain}.nofasta.gff3 > ./${strain}_borders.table 
 
 mkdir borders
 mv ./${strain}.virbox ./borders/
@@ -464,7 +464,7 @@ echo -e "Identifying biosynthetic gene clusters (antiSMASH)"
 echo -e ""
 
 if $antismash_run; then
-    antismash ${strain}.gbff --cpus $thread --output-dir antiSMASH $antismash_args || error_exit "error occurred while running antiSMASH" 
+    antismash ${strain}_cds_subset.gbk --cpus $thread --output-dir antiSMASH $antismash_args || error_exit "error occurred while running antiSMASH" 
     python $BEAV_DIR/scripts/antismash_genbanks_to_table.py -i./antiSMASH -o ${strain}_antismash.table
 	echo -e ""
 	echo -e "Done"
@@ -480,9 +480,8 @@ echo -e "Identifying phage (DBSCAN-SWA)"
 echo -e ""
 
 if $dbscanswa_run; then
-	cp ${strain}.gbff ${strain}.gbk
-	sed -i 's/gnl|Bakta|//g' ${strain}.gbk
-	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}.gbk --output DBSCAN-SWA --thread_num "$thread" | tee dbscan-swa.log || error_exit "error occurred while running DBSCAN-SWA"
+	sed -i 's/gnl|Bakta|//g' ${strain}_cds_subset.gbk
+	python $BEAV_DIR/software/DBSCAN-SWA/bin/dbscan-swa.py --input ${strain}_cds_subset.gbk --output DBSCAN-SWA --thread_num "$thread" | tee dbscan-swa.log || error_exit "error occurred while running DBSCAN-SWA"
 	cut -f 2,5-8 ./DBSCAN-SWA/bac_DBSCAN-SWA_prophage_summary.txt | grep -v "bacteria_id" > prophage.table
 
 	echo -e ""
