Update defensefinder and borders log

diff --git a/beav b/beav
--- a/beav
+++ b/beav
@@ -401,8 +401,8 @@ if $bakta_run; then
 	echo -e "Done" | tee -a Beav.log
 	echo -e "" | tee -a Beav.log
 fi
-mv Bakta.log $strain
-mv Beav.log $strain
+mv Bakta.log $strain 2> /dev/null
+mv Beav.log $strain 2> /dev/null
 cd $strain
 
 mkdir tables 2> /dev/null
@@ -533,8 +533,8 @@ if $agrobacterium_run; then
 	nhmmer --tblout "$strain".leftborder $BEAV_DIR/models/T-DNA_leftborder.hmm bakta/"$strain".fna >> borders.log 
 	nhmmer --tblout "$strain".rightborder $BEAV_DIR/models/T-DNA_rightborder.hmm bakta/"$strain".fna >> borders.log
 	nhmmer --tblout "$strain".overdrive $BEAV_DIR/models/overdrive.hmm bakta/"$strain".fna >> borders.log
-	fuzznuc --sequence bakta/"$strain".fna --pattern RTTDCAWWTGHAAY -outfile ${strain}.virbox -rformat excel --complement 2>&1 >> borders.log
-	fuzznuc --sequence bakta/"$strain".fna --pattern WNGTGMARAWYTGCACDW -outfile ${strain}.trabox -rformat excel --complement 2>&1 >> borders.log
+	fuzznuc --sequence bakta/"$strain".fna --pattern RTTDCAWWTGHAAY -outfile ${strain}.virbox -rformat excel --complement >> borders.log 2>&1
+	fuzznuc --sequence bakta/"$strain".fna --pattern WNGTGMARAWYTGCACDW -outfile ${strain}.trabox -rformat excel --complement >> borders.log 2>&1
 	mv ${strain}.leftborder  ./borders/${strain}.left_T-DNA_border
         mv ${strain}.rightborder  ./borders/${strain}.right_T-DNA_border
         mv ${strain}.overdrive  ./borders/
@@ -545,8 +545,8 @@ fi
 nhmmer --tblout "$strain".dif $BEAV_DIR/models/dif.hmm bakta/"$strain".fna >> borders.log
 nhmmer --tblout "$strain".nodbox $BEAV_DIR/models/nodbox.hmm bakta/"$strain".fna >> borders.log
 nhmmer --tblout "$strain".ttsbox $BEAV_DIR/models/ttsbox.hmm bakta/"$strain".fna >> borders.log
-fuzznuc -pattern 'GGAAC[CT]N(15,17)CCACNNA' -sequence bakta/"$strain".fna -complement -outfile ${strain}.hrp_box.out -rformat excel 2>&1 >> borders.log
-fuzznuc -pattern 'TTCGBN(15)TTCGB' -sequence bakta/"$strain".fna -complement -outfile ${strain}.pip_box.out -rformat excel 2>&1 >> borders.log
+fuzznuc -pattern 'GGAAC[CT]N(15,17)CCACNNA' -sequence bakta/"$strain".fna -complement -outfile ${strain}.hrp_box.out -rformat excel >> borders.log 2>&1
+fuzznuc -pattern 'TTCGBN(15)TTCGB' -sequence bakta/"$strain".fna -complement -outfile ${strain}.pip_box.out -rformat excel >> borders.log 2>&1
 
 mv ./${strain}.pip_box.out ./borders/
 mv ./${strain}.hrp_box.out ./borders/
@@ -711,7 +711,7 @@ fi
 
 if $defensefinder_run; then
 	SECONDS=0
-	defense-finder run --db-type gembase ./bakta/${strain}.faa > defensefinder.log || error_exit "error occurred while running DefenseFinder. Please see defensefinder.log" | tee -a Beav.log
+	defense-finder run --db-type gembase ./bakta/${strain}.faa > defensefinder.log 2>&1 || error_exit "error occurred while running DefenseFinder. Please see defensefinder.log" | tee -a Beav.log
 	ELAPSED="Elapsed: $(($SECONDS / 3600))hrs $((($SECONDS / 60) % 60))min $(($SECONDS % 60))sec"
 	echo $ELAPSED | tee -a Beav.log
 	cut -f 2,3 ./${strain}_defense_finder_genes.tsv | grep -v 'hit_id' > ${strain}_defensefinder.tsv.table
